steps:
  - uses: actions/checkout@v2.3.2
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v4
    name: Build & push Docker image
    with:
      image: repo/image
      tag: latest
      registry: registry-url.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKETHUB_USERNAME }}
      password: ${{ secrets.DOCKETHUB_TOKEN }}
      repository: jrwtango/c2express001
      tag_with_ref: true
